Repository DeveloperAcademy-POSTECH/MacC-Team-WindUp, pull requests merged in 2023-10, with the labels that each got.

#20 [Settings] github push test
  highpitch.xcodeproj/project.pbxproj
  highpitch/APIs/ReturnZero/ReturnzeroAPI.swift
Labels: Setting

#26 Add#25 발표 예시 데이터 추가
  highpitch.xcodeproj/project.pbxproj
  highpitch/Resource/Embaded/test1.m4a
  highpitch/Resource/Embaded/test1_json.json
  highpitch/Resource/Embaded/test1_response.txt
  highpitch/Resource/Embaded/test2.m4a
  highpitch/Resource/Embaded/test2_json.json
  highpitch/Resource/Embaded/test2_response.txt
Labels: Add

#28 MainWindow 뷰 구조 작성
  .github/PULL_REQUEST_TEMPLATE.md
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/PrimaryScale/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/PrimaryScale/primary500.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/test.colorset/Contents.json
  highpitch/Managers/NotificationManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Models/PersistenceModels/SampleModel/SampleModel.swift
  highpitch/Presentation/Components/HPButton.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectLinkItem/ProjectLinkItem.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
  highpitch/Resource/Embaded/Projects.json
  highpitch/Utils/Extension/Color+Extension.swift
  highpitch/Utils/Extension/Date+Extension.swift
  highpitch/Utils/Extension/String+Extension.swift
  highpitch/Utils/Extension/View+Extension.swift
  highpitch/Utils/Modifier/ShapeModifier.swift
Labels: Feat

#30 [Setting] 샘플 프로젝트 모델 수정 및 추가
  .swiftlint.yml
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/FileSystemManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Models/DataModels/Practice.swift
  highpitch/Models/DataModels/Project.swift
  highpitch/Models/DataModels/SampleProjectJson.swift
  highpitch/Models/DataModels/Utterance.swift
  highpitch/Models/PersistenceModels/Practice.swift
  highpitch/Models/PersistenceModels/ProjectModel.swift
  highpitch/Models/PersistenceModels/Utterence.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift
  highpitch/Resource/Embaded/test1.json
  highpitch/Resource/Embaded/test2.json
  highpitch/Resource/Embaded/test2_response.txt
Labels: Setting

#32 Feature/#27 done with creating data for chart
  highpitch.xcodeproj/project.pbxproj
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
Labels: Feat

#41 [Feat] 로그인 기능 구현 #37
  highpitch.xcodeproj/project.pbxproj
  highpitch/APIs/ReturnZero/ReturnzeroAPI.swift
  highpitch/Managers/AuthManager.swift
  highpitch/Managers/KeyChainManager.swift
  highpitch/Models/DataModels/TokenData.swift
  highpitchTests/highpitchTests.swift
Labels: Feat

#42 [Feat] 오디오 재생 녹음 기능 구현 #40
  highpitch.xcodeproj/project.pbxproj
  highpitch/Managers/AudioManager.swift
Labels: Feat

#43 [Design] 디자인 시스템 코드 작성
  highpitch.xcodeproj/project.pbxproj
  highpitch/DesignSystem/Components/Common/HPSegmentedControl.swift
  highpitch/DesignSystem/Components/Common/HPStyledLabel.swift
  highpitch/DesignSystem/Components/Common/HPTooltip.swift
  highpitch/DesignSystem/Components/Common/HPTopToolbar.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.swift
  highpitch/DesignSystem/Foundation/Layout/Space.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectLinkItem/ProjectLinkItem.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
  highpitch/Utils/Modifier/LabelModifier.swift
Labels: Add, Design

#44 Refactor/#38 기존 데이터들 SwiftData Model으로 교체
  ProjectModel.xcdatamodeld/ProjectModel.xcdatamodel/contents
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/FileSystemManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Models/PersistenceModels/ProjectModel.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
Labels: Refactor

#46 Feature/#27 done with chart.(except UI)
  highpitch.xcodeproj/project.pbxproj
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift
Labels: Feat

#48 Feat/#45 메인 뷰와 연습 상세 보기 데이터 연동
  highpitch.xcodeproj/project.pbxproj
  highpitch/Managers/AudioManager.swift
  highpitch/Models/PersistenceModels/PracticeModel.swift
  highpitch/Models/PersistenceModels/ProjectModel.swift
  highpitch/Models/PersistenceModels/UtteranceModel.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
Labels: Feat

#52 [Feat] MainWindowView와 MenubarExtraView 데이터 연동
  highpitch.xcodeproj/project.pbxproj
  highpitch/APIs/ReturnZero/ReturnzeroAPI.swift
  highpitch/Managers/AudioManager.swift
  highpitch/Managers/KeyChainManager.swift
  highpitch/Managers/MediaManager.swift
  highpitch/Models/PersistenceModels/PracticeModel.swift
  highpitch/Models/PersistenceModels/UtteranceModel.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/SecretKey.plist
Labels: Feat

#54 Feature/#47 ScriptView done
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
Labels: Feat

#57 [Design] 디자인 레이아웃 및 차트 레이아웃 정리
  .gitattributes
  highpitch.xcodeproj/project.pbxproj
  highpitch/APIs/ReturnZero/ReturnzeroAPI.swift
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Components/Common/HPStyledLabel.swift
  highpitch/DesignSystem/Components/Common/HPTopToolbar.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/6_Component/audioController.colorset/Contents.json
  highpitch/DesignSystem/Foundation/Typography/Typography.swift
  highpitch/Managers/AudioManager.swift
  highpitch/Managers/AuthManager.swift
  highpitch/Managers/FileSystemManager.swift
  highpitch/Managers/MediaManager.swift
  highpitch/Managers/PracticeManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Models/DataModels/FillerWord.swift
  highpitch/Models/DataModels/SampleProjectJson.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/Utils/Extension/Bundle+Extension.swift
  highpitch/extension/Bundel+extension.swift
Labels: Design, Chore

#61 Feature/#58 Done with creating PracticeModel
  highpitch.xcodeproj/project.pbxproj
  highpitch/DesignSystem/Foundation/Colors/Colors.swift
  highpitch/Managers/PracticeManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Models/DataModels/FillerWord.swift
  highpitch/Models/PersistenceModels/FillerWordModel.swift
  highpitch/Models/PersistenceModels/PracticeModel.swift
  highpitch/Models/PersistenceModels/PracticeSummaryModel.swift
  highpitch/Models/PersistenceModels/SentenceModel.swift
  highpitch/Models/PersistenceModels/WordModel.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
Labels: Feat, Refactor

#62 [Feat] MenubarExtra Picker 커스텀 작성
  highpitch.xcodeproj/project.pbxproj
  highpitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Components/Common/HPMenu.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraContent/MenubarExtraContent.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/Presentation/PlayBar/PlayBar.swift
  highpitch/Presentation/Settings/SettingsView.swift
Labels: Design, Feat

#63 Feature/#58 practiceModel connected with chartView
  highpitch/Managers/PracticeManager.swift
  highpitch/Models/PersistenceModels/PracticeModel.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
Labels: Feat, Refactor

#66 [Feat] ReturnZero API 연동
  .gitignore
  highpitch/APIs/ReturnZero/ReturnzeroAPI.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.xcassets/6_Component/audiocontroller.colorset/Contents.json
  highpitch/Managers/KeyChainManager.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/SecretKey.plist
Labels: Feat

#68 [Chore] 전체 플로우 기능 테스트
  highpitch.xcodeproj/project.pbxproj
  highpitch.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  highpitch/Managers/PracticeManager.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraContent/MenubarExtraContent.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraContent/PracticeResultCell.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/SecretKey.plist
Labels: Chore

#70 [Feat] ExtraMenubar 작성
  highpitch/Managers/AppleScriptManager.swift
  highpitch/Managers/KeynoteManager.swift
  highpitch/Managers/PracticeManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraContent/MenubarExtraContent.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraContent/PracticeResultCell.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/Utils/Modifier/LabelModifier.swift
Labels: Feat

#72 [Design] 연습 회차별 탭 UI 그리기
  highpitch/APIs/ReturnZero/ReturnzeroAPI.swift
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/KeyChainManager.swift
  highpitch/Models/PersistenceModels/PracticeModel.swift
  highpitch/Models/PersistenceModels/UtteranceModel.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
  highpitch/SecretKey.plist
  highpitch/Utils/Extension/Date+Extension.swift
Labels: Design

#73 Feat/#71 전체연습 통계 설정 중
  highpitch.xcodeproj/project.pbxproj
  highpitch/DesignSystem/Components/Common/HPSegmentedControl.swift
  highpitch/DesignSystem/Components/Common/HPStyledLabel.swift
  highpitch/DesignSystem/Components/Common/HPTooltip.swift
  highpitch/DesignSystem/Foundation/Colors/Colors.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
  highpitch/SecretKey.plist
Labels: Design, Feat

#74 [Feat] #71 chart UI 및 데이터 연동
  highpitch/DesignSystem/Components/Common/HPSegmentedControl.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
  highpitch/Utils/Extension/Date+Extension.swift
Labels: Design, Feat

#76 [Design] 연습 탭 체크박스 뷰 그리기
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
Labels: Design

#79 [Feat] ReturnzeroApiV2 구현 #77
  highpitch.xcodeproj/project.pbxproj
  highpitch/APIs/ReturnZero/ReturnzeroAPIV2.swift
Labels: Feat

#82 [Feat] LocalNotification으로 뷰 이동 로직 구현 #88
  highpitch/Managers/NotificationManager.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
Labels: Feat

#85 [Feat] SettingView 틀 구성
  highpitch/Presentation/Settings/SettingsView.swift
Labels: Feat

#87 [Feat] PracticeList 뷰 작성
  highpitch.xcodeproj/project.pbxproj
  highpitch/DesignSystem/Components/Common/HPTooltip.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MainWindow/ProjectView/ProjectView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraContent/MenubarExtraContent.swift
Labels: Design, Feat

#88 Feat/#78 PracticeView 마무리
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Components/Common/HPTooltip.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
Labels: Design, Feat

#89 [Fix] PracticeView 뷰 최적화
  highpitch.xcodeproj/project.pbxproj
  highpitch/APIs/ReturnZero/ReturnzeroAPIV2.swift
  highpitch/Managers/MediaManager.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_1024 1.png
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_1024.png
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_128.png
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_16.png
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_256 1.png
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_256.png
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_32 1.png
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_32.png
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_512 1.png
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_512.png
  highpitch/Resource/Assets.xcassets/AppIcon.appiconset/appLogo_64.png
Labels: Design, Feat

#91 [Feat] Keyboard Shortcuts 구현
  highpitch.xcodeproj/project.pbxproj
  highpitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/Settings/SettingsView.swift
Labels: Feat

#92 [Fix] 단어 없는 연습 저장 안하기
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
Labels: Fix

#93 [Design] SettingView 완성
  highpitch/Presentation/Settings/SettingsView.swift
  highpitch/Resource/Assets.xcassets/ESC.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/ESC.imageset/ESC.png
  highpitch/Resource/Assets.xcassets/ESC.imageset/ESC@2x.png
  highpitch/Resource/Assets.xcassets/ESC.imageset/ESC@3x.png
  highpitch/Resource/Assets.xcassets/F5.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/F5.imageset/F5.png
  highpitch/Resource/Assets.xcassets/F5.imageset/F5@2x.png
  highpitch/Resource/Assets.xcassets/F5.imageset/F5@3x.png
  highpitch/Resource/Assets.xcassets/Feedback.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/Feedback.imageset/Feedback.png
  highpitch/Resource/Assets.xcassets/Feedback.imageset/Feedback@2x.png
  highpitch/Resource/Assets.xcassets/Feedback.imageset/Feedback@3x.png
  highpitch/Resource/Assets.xcassets/Space.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/Space.imageset/Space.png
  highpitch/Resource/Assets.xcassets/Space.imageset/Space@2x.png
  highpitch/Resource/Assets.xcassets/Space.imageset/Space@3x.png
Labels: Design

#94 [Fix] 내부 쇼케이스용 빌드
  highpitch/App/HighPitchApp.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
Labels: Chore

#96 [Refactor] 불필요한 코드 삭제
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/AudioManager.swift
  highpitch/Managers/FileSystemManager.swift
  highpitch/Managers/KeynoteManager.swift
  highpitch/Managers/MediaManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Models/DataModels/MyModel.swift
  highpitch/Models/DataModels/Practice.swift
  highpitch/Models/DataModels/Project.swift
  highpitch/Models/DataModels/SampleProjectJson.swift
  highpitch/Models/PersistenceModels/SampleModel/SampleModel.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/Presentation/Settings/SettingsView.swift
Labels: Refactor

#97 [Refactor] 테스트용 데이터 삭제 + 프로젝트 삭제 버튼 추가
  highpitch.xcodeproj/project.pbxproj
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Resource/Embaded/test1.json
  highpitch/Resource/Embaded/test1.key
  highpitch/Resource/Embaded/test1.m4a
  highpitch/Resource/Embaded/test1_json.json
  highpitch/Resource/Embaded/test1_response.txt
  highpitch/Resource/Embaded/test2.json
  highpitch/Resource/Embaded/test2.key
  highpitch/Resource/Embaded/test2.m4a
  highpitch/Resource/Embaded/test2_json.json
  highpitch/Resource/Embaded/test2_response.txt
Labels: Refactor

#98 [Docs] Update README.md
  README.md
Labels: Docs

#100 [Docs] README.md 내 Member 업데이트
  README.md
Labels: Docs

#101 [Refactor] MenubarExtra stopRecording 함수 정리 및 개선
  highpitch/Managers/MediaManager.swift
  highpitch/Managers/PracticeManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Models/PersistenceModels/UtteranceModel.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
Labels: Chore, Refactor

#102 [Refactor] MenubarExtraHeader 코드 정리 및 디자인 시스템 컴포넌트 추가
  .swiftlint.yml
  highpitch.xcodeproj/project.pbxproj
  highpitch/DefaultSample/ContentView.swift
  highpitch/DefaultSample/Item.swift
  highpitch/DefaultSample/highpitchApp.swift
  highpitch/DesignSystem/Components/Common/HPTopToolbar.swift
  highpitch/DesignSystem/Components/Core/HPButton/HPButton.swift
  highpitch/DesignSystem/Components/Core/HPLabel/HPLabel.swift
  highpitch/DesignSystem/Foundation/Layout/Space.swift
  highpitch/DesignSystem/Foundation/Styles/BaseStyle.swift
  highpitch/DesignSystem/Foundation/Styles/HPButtonStyle.swift
  highpitch/DesignSystem/Foundation/Styles/HPLabelStyle.swift
  highpitch/DesignSystem/Foundation/Typography/Typography.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Presentation/Components/HPButton.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Utils/Extension/String+Extension.swift
  highpitch/Utils/Modifier/LabelModifier.swift
Labels: Design, Chore, Refactor, Del

#103 Refactor/#95 ProjectManager 및 StatisticTabItem refactor
  highpitch.xcodeproj/project.pbxproj
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/PracticeManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Models/PersistenceModels/PracticeSummaryModel.swift
  highpitch/Models/PersistenceModels/SentenceModel.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticTabGraph.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
Labels: Refactor
