Repository DeveloperAcademy-POSTECH/MacC-Team-WindUp, pull requests merged in 2023-11, with the labels that each got.

#107 [Feat] 프로젝트 삭제 시 해당 프로젝트 밑에 연습들 오디오파일 삭제
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeList.swift
Labels: Feat

#109 [Refactor] 앱 실행시 Keyboard Shortcut(Hotkey) 적용
  highpitch/App/HighPitchApp.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
Labels: Refactor

#111 [Feat] 세팅 뷰 구현 #110
  highpitch.xcodeproj/project.pbxproj
  highpitch/Presentation/Settings/FeedbackSettingView.swift
  highpitch/Presentation/Settings/GeneralSettingView.swift
  highpitch/Presentation/Settings/SettingsView.swift
Labels: Feat

#113 [Refactor] 메인뷰, 엑스트라메뉴바 레이아웃 오류 수정, 메뉴바 아이콘 추가
  highpitch.xcodeproj/project.pbxproj
  highpitch/APIs/ReturnZero/ReturnzeroAPIV2.swift
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Components/Common/HPTopToolbar.swift
  highpitch/Managers/MediaManager.swift
  highpitch/Managers/PracticeManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Managers/SystemManager.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectLinkItem/ProjectLinkItem.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraFooter/MenubarExtraFooter.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/Presentation/Overlay/OverlayView.swift
  highpitch/Resource/Assets.xcassets/loader/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-0.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-0.imageset/menubar-loading-dark-0.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-1.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-1.imageset/menubar-loading-dark-1.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-2.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-2.imageset/menubar-loading-dark-2.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-3.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-3.imageset/menubar-loading-dark-3.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-4.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-4.imageset/menubar-loading-dark-4.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-5.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-5.imageset/menubar-loading-dark-5.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-6.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-6.imageset/menubar-loading-dark-6.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-7.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-7.imageset/menubar-loading-dark-7.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-0.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-0.imageset/menubar-loading-light-0.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-1.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-1.imageset/menubar-loading-light-1.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-2.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-2.imageset/menubar-loading-light-2.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-3.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-3.imageset/menubar-loading-light-3.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-4.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-4.imageset/menubar-loading-light-4.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-5.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-5.imageset/menubar-loading-light-5.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-6.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-6.imageset/menubar-loading-light-6.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-7.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-light-7.imageset/menubar-loading-light-7.png
  highpitch/Resource/Assets.xcassets/loader/menubar-noti-dark.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-noti-dark.imageset/menubar-noti-dark.png
  highpitch/Resource/Assets.xcassets/loader/menubar-noti-light.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-noti-light.imageset/menubar-noti-lignt.png
Labels: Refactor

#115 Refactor/#95 several bug fixed, UI changed
  highpitch/DesignSystem/Components/Common/HPSegmentedControl.swift
  highpitch/Managers/PracticeManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Models/PersistenceModels/PracticeSummaryModel.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeList/PracticeListCell.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordDetail.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FillerWordList.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsagePercentChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/UsageTopTierChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/PracticeView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticesTabItem.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticTabGraph.swift
  highpitch/Presentation/MainWindow/ProjectView/StatisticsTabItem.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraFooter/MenubarExtraFooter.swift
Labels: Refactor

#117 Refactor/#95 speechAverage chart 및 fastSentReplay
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/PracticeManager.swift
  highpitch/Models/PersistenceModels/PracticeSummaryModel.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackChartView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/SpeedAverageChart.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/ScriptView/ScriptView.swift
Labels: Refactor

#120 [Fix] 빠르게 말한 구간 오디오 싱크 수정 #119
  highpitch/Managers/MediaManager.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/AudioControllerView/AudioControllerView.swift
  highpitch/Presentation/MainWindow/ProjectView/PracticeView/FeedbackChartView/FeedbackCharts/FastSentReplay.swift
Labels: Fix

#122 [Fix] notification 뷰 이동 로직 수정 #119
  highpitch/Managers/ProjectManager.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
Labels: Fix

#123 [Fix] 노티피케이션 등 UI 오류 수정
  highpitch/App/HighPitchApp.swift
  highpitch/DesignSystem/Components/Common/HPMenu.swift
  highpitch/DesignSystem/Components/Common/HPTopToolbar.swift
  highpitch/DesignSystem/Components/Core/HPList/HPListCell.swift
  highpitch/Managers/MediaManager.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Presentation/MainWindow/MainWindowView.swift
  highpitch/Presentation/MainWindow/ProjectNavigationLink/ProjectNavigationLinkView.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraFooter/MenubarExtraFooter.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraView.swift
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-0.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-0.imageset/menubar-loading-dark-0.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-1.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-1.imageset/menubar-loading-dark-1.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-2.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-2.imageset/menubar-loading-dark-2.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-3.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-3.imageset/menubar-loading-dark-3.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-4.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-4.imageset/menubar-loading-dark-4.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-5.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-5.imageset/menubar-loading-dark-5.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-6.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-6.imageset/menubar-loading-dark-6.png
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-7.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-loading-dark-7.imageset/menubar-loading-dark-7.png
  highpitch/Resource/Assets.xcassets/loader/menubar-noti-dark.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-noti-dark.imageset/menubar-noti-dark.png
  highpitch/Resource/Assets.xcassets/loader/menubar-noti-light.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-noti-light.imageset/menubar-noti-lignt.png
  highpitch/Resource/Assets.xcassets/loader/menubar-noti-lignt.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-noti-lignt.imageset/menubar-noti-lignt.svg
  highpitch/Resource/Assets.xcassets/loader/menubar-noti.symbolset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/menubar-noti.symbolset/noti.svg
  highpitch/Resource/Assets.xcassets/loader/test-noti.imageset/Contents.json
  highpitch/Resource/Assets.xcassets/loader/test-noti.imageset/test-noti.svg
Labels: Chore, Fix

#124 [Feat] SettingView에서 키보드바인딩 커스텀 기능 추가
  highpitch/App/HighPitchApp.swift
  highpitch/Managers/SystemManager.swift
  highpitch/Presentation/Settings/GeneralSettingView.swift
  highpitch/Presentation/Settings/SettingsView.swift
Labels: Feat

#126 [Chore] 배포 버전 빌드
  highpitch/App/HighPitchApp.swift
  highpitch/App/Info.plist
  highpitch/DesignSystem/Components/Common/HPTopToolbar.swift
  highpitch/Managers/ProjectManager.swift
  highpitch/Presentation/MenubarExtra/MenubarExtraHeader/MenubarExtraHeader.swift
Labels: Chore
